// Authentication configuration constants

export const AUTH_CONFIG = {
	ACCESS_TOKEN_EXPIRY_MINUTES: 30,
	REFRESH_TOKEN_EXPIRY_DAYS: 30,
	REFRESH_COOLDOWN_MINUTES: 5,
	OTP_EXPIRY_MINUTES: 5,
	OTP_COOLDOWN_MINUTES: 1,
	OTP_MAX_ATTEMPTS: 3,
} as const
